aggregation/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page  # noqa: F401

from . import views


app_name = "aggregation"

urlpatterns = [
    # path('', cache_page(10)(views.index), name='index'),  # ToDo: cached!
    path('', views.index, name='index'),

    path('author_list/', views.AuthorListView.as_view(), name='author-list'),
    path('publisher_list/', views.PublisherListView.as_view(), name='publisher-list'),
    path('store_list/', views.StoreListView.as_view(), name='store-list'),

    path('book_list/', views.BookListView.as_view(), name='book-list'),
    path('book/create/', views.BookCreateView.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdateView.as_view(), name='book-update'),
    path('book<int:pk>/delete/', views.BookDeleteView.as_view(), name='book-confirm-delete'),
    path('contact_form/', views.ContactFormView.as_view(), name='contact-form'),
    path('contact_form/thanks/', views.ContactTemplateView.as_view(), name='contact-form-thanks'),

    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
    path('publisher/<int:pk>/', views.PublisherDetailView.as_view(), name='publisher-detail'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('store/<int:pk>/', views.StoreDetailView.as_view(), name='store-detail'),

    path('reminder_form', views.reminder_form, name='reminder-form'),
]

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name="base_project_page.html"), name='base_project_page'),
    path('aggregation/', include('aggregation.urls')),
    path('quote/', include('quote.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

quote/urls.py
from django.urls import path

from . import views


app_name = "quote"

urlpatterns = [
    path('', views.index, name='index'),

    path('author_list/', views.AuthorListView.as_view(), name='author-list'),
    path('quote_list/', views.QuoteListView.as_view(), name='quote-list'),

    path('author_detail/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
    path('quote_detail/<int:pk>/', views.QuoteDetailView.as_view(), name='quote-detail'),
]

quote/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Author(models.Model):
    """Model representing an author of quote."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    place_of_birth = models.CharField(max_length=100)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('quote:author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.first_name} {self.last_name} '


class Quote(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    # Foreign Key used because quote can only have one author, but authors can have multiple quotes
    text = models.TextField(max_length=1000)

    class Meta:
        ordering = ['author', 'title']

    def get_absolute_url(self):
        return reverse('quote:quote-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.title

quote/views.py
from django.db.models import Count
from django.shortcuts import render
from django.views import generic

from quote.models import Author, Quote


# Create your views here.
def index(request):
    """View function for home page of Quote site."""
    # Generate counts of some of the main objects
    num_authors = Author.objects.count()
    num_quotes = Quote.objects.count()

    context = {
        'num_authors': num_authors,
        'num_quotes': num_quotes,
    }
    return render(request, 'quote/index.html', context=context)


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 20
    template_name = "quote/author_list.html"

    def get_queryset(self):
        return super().get_queryset().order_by('first_name')


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = "quote/author_detail.html"

    # author_quotes
    def get_context_data(self, **kwargs):
        context = super(AuthorDetailView, self).get_context_data(**kwargs)
        author_quotes = Quote.objects.filter(author__id=self.object.id).annotate(num=Count("id"))
        context['author_quotes'] = author_quotes
        context['quotes_total'] = len(author_quotes)
        return context


class QuoteListView(generic.ListView):
    model = Quote
    template_name = "quote/quote_list.html"
    paginate_by = 10


class QuoteDetailView(generic.DetailView):
    model = Quote
    template_name = "quote/quote_detail.html"

    def get_context_data(self, **kwargs):
        context = super(QuoteDetailView, self).get_context_data(**kwargs)
        context['quote_author'] = Author.objects.get(id=self.object.author_id)
        return context

quote/templates/quote/author_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Author Quote Detail</title>
</head>
<body>

{% extends "quote/base_generic.html" %}

{% block content %}
  <h1>Author: {{ author }}</h1>

  <p><strong>Name:</strong> {{ author.first_name }}</p>
  <p><strong>Surname:</strong> {{ author.last_name }}</p>
  <p><strong>Date of birth:</strong> {{ author.date_of_birth }}</p>
  <p><strong>Place of birth:</strong> {{ author.place_of_birth }}</p>
  <p><strong>Quotes total</strong> {{ quotes_total }}</p>


<div style="margin-left:20px;margin-top:20px">
<h4>Quotes</h4>
<dl>

{% for quote in author_quotes %}
  <dt><a href="{% url 'quote:quote-detail' quote.pk %}">{{quote.title}}</a> ("{{ quote.text }}",   ID: {{ quote.pk }})

{% endfor %}
</dl>

</div>

{% endblock %}

</body>
</html>

quote/templates/quote/author_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Author Quotes List</title>
</head>
<body>

{% extends "quote/base_generic.html" %}

{% block content %}
  <h1>Author Quotes List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author }}</a>    (ID: {{ author.id }})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no Authors.</p>
  {% endif %}
{% endblock %}

</body>
</html>

quote/templates/quote/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Quote Application</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'base_project_page' %}">Base PROJECT Page</a></li>
<hr>
          <li><a href="{% url 'quote:index' %}">Home Quote App Page</a></li>
<hr>
          <li><a href="{% url 'quote:author-list' %}">All Authors</a></li>
          <li><a href="{% url 'quote:quote-list' %}">All Quotes</a></li>
{#          <li><a href="{% url 'aggregation:book-list' %}">All Books</a></li>#}
{#          <li><a href="{% url 'aggregation:store-list' %}">All Stores</a></li>#}
{#<hr>#}
{#          <li><a href="{% url 'aggregation:reminder_form' %}">Reminder</a></li>#}

        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">

        {% block content %}
        {% endblock %}

        {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %}

      </div>
    </div>
  </div>
</body>
</html>

quote/templates/quote/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quote App Index Page</title>
</head>
<body>

{% extends "quote/base_generic.html" %}

{% block content %}
  <h1>Quote App Home Page</h1>
  <p>Welcome to <em>Quote App</em>!</p>
  <h2>Dynamic content</h2>
  <p>There are the following record counts:</p>
  <ul>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Quotes:</strong> {{ num_quotes }}</li>

  </ul>

{% endblock %}

</body>
</html>

quote/templates/quote/quote_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quote Detail</title>
</head>
<body>

{% extends "quote/base_generic.html" %}

{% block content %}

  <h2>Quote:</h2>
<hr>

  <h1>"{{ quote.text }}"</h1>

  <p><strong>Author:</strong></p>
    {% if quote_author %}
        <a href="{{ quote_author.get_absolute_url }}"> {{ quote_author }} </a>

    {% else %}
    <p>No available Author has the Quote.</p>
    {% endif %}

{% endblock %}

</body>
</html>

quote/templates/quote/quote_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quote List</title>
</head>
<body>

{% extends "quote/base_generic.html" %}

{% block content %}
  <h1>Quote List</h1>
  {% if quote_list %}
  <ul>
    {% for quote in quote_list %}
      <li>
        <a href="{{ quote.get_absolute_url }}">{{ quote }}</a> (ID: {{ quote.id }},
          "{{ quote.text }}")
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no Quotes.</p>
  {% endif %}
{% endblock %}

</body>
</html>