aggregation/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page  # noqa: F401

from . import views


app_name = "aggregation"

urlpatterns = [
    # path('', cache_page(10)(views.index), name='index'),  # ToDo: cached!
    path('', views.index, name='index'),

    path('author_list/', views.AuthorListView.as_view(), name='author-list'),
    path('publisher_list/', views.PublisherListView.as_view(), name='publisher-list'),
    path('store_list/', views.StoreListView.as_view(), name='store-list'),

    path('book_list/', views.BookListView.as_view(), name='book-list'),
    path('book/create/', views.BookCreateView.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdateView.as_view(), name='book-update'),
    path('book<int:pk>/delete/', views.BookDeleteView.as_view(), name='book-confirm-delete'),
    path('contact_form/', views.ContactFormView.as_view(), name='contact-form'),
    path('contact_form/thanks/', views.ContactTemplateView.as_view(), name='contact-form-thanks'),

    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
    path('publisher/<int:pk>/', views.PublisherDetailView.as_view(), name='publisher-detail'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('store/<int:pk>/', views.StoreDetailView.as_view(), name='store-detail'),

    path('reminder_form', views.reminder_form, name='reminder-form'),
]

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name="base_project_page.html"), name='base_project_page'),
    path('aggregation/', include('aggregation.urls')),
    path('quote/', include('quote.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

aggregation/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()

    def get_absolute_url(self):
        return reverse('aggregation:author-detail', args=[str(self.id)])

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=300)

    def get_absolute_url(self):
        return reverse('aggregation:publisher-detail', args=[str(self.id)])

    def __str__(self):
        return self.name


class Book(models.Model):
    name = models.CharField(max_length=300)
    pages = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    rating = models.FloatField()
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    pubdate = models.DateField()

    def get_absolute_url(self):
        return reverse('aggregation:book-detail', args=[str(self.id)])

    def __str__(self):
        return self.name


class Store(models.Model):
    name = models.CharField(max_length=300)
    books = models.ManyToManyField(Book)

    def get_absolute_url(self):
        return reverse('aggregation:store-detail', args=[str(self.id)])

    def __str__(self):
        return self.name

aggregation/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


def proper_date(value):
    now = timezone.now()
    future = now + datetime.timedelta(milliseconds=172_800_000)  # Exactly 48 hours
    if (value < now) or (value > future):
        raise ValidationError(
            _('Not Past, not Future more than 2 days.'),
            params={'value': value},
        )


class ReminderForm(forms.Form):
    email = forms.EmailField(
        label="Email",
        help_text='Enter a valid Email for receiving the Reminder.',
    )

    reminder_text = forms.CharField(
        label="Reminder",
        widget=forms.Textarea(attrs={"rows": "5"}),
        help_text='Write down your reminder, please.',
    )

    date_time = forms.DateTimeField(
        label="Date&Time",
        help_text='Enter a valid Day and Time when you will receive the Reminder.\n'
                  'Not Past, not Future more than 2 days',
        validators=[proper_date],
    )


class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email_address = forms.EmailField(max_length=150)
    message = forms.CharField(widget=forms.Textarea, max_length=2000)

    def send_email(self):
        subject = "Website Inquiry."
        body = {
            'first_name': self.cleaned_data['first_name'],
            'last_name': self.cleaned_data['last_name'],
            'email': self.cleaned_data['email_address'],
            'message': self.cleaned_data['message'],
        }
        message = "\n".join(body.values())
        try:
            send_mail(subject, message, 'admin@noreply.com', ['admin@noreply.com'])
        except BadHeaderError:
            return HttpResponse('Invalid header found.')

aggregation/views.py
from aggregation.forms import ContactForm
from aggregation.forms import ReminderForm
from aggregation.models import Author, Book, Publisher, Store
from aggregation.tasks import tasks

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.db.models import Avg, Count
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.datetime_safe import datetime
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.cache import cache_page
from django.views.generic.edit import CreateView, DeleteView, FormView, UpdateView


CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)

# Create your views here.


@method_decorator(cache_page(CACHE_TTL), "get")  # ToDo: cached!
class BookListView(generic.ListView):
    template_name = "aggregation/book_list.html"
    model = Book
    paginate_by = 750
    context_object_name = "books"

    def get_queryset(self):
        return Book.objects.select_related("publisher").order_by('name')

    # @method_decorator(cache_page(CACHE_TTL))  # ToDo: cached!
    # def dispatch(self, request, *args, **kwargs):
    #     return super().dispatch(request, *args, **kwargs)

    # @method_decorator(cache_page(CACHE_TTL))  # ToDo: cached!
    # def get(self, request, *args, **kwargs):
    #     return super().get(request, *args, **kwargs)


# @cache_page(CACHE_TTL)
def index(request):
    """View function for home page of site."""
    # Generate counts of some of the main objects
    num_authors = Author.objects.count()
    num_publishers = Publisher.objects.count()
    num_books = Book.objects.count()
    num_stores = Store.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        'num_authors': num_authors,
        'num_publishers': num_publishers,
        'num_books': num_books,
        'num_stores': num_stores,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


# List Views
class AuthorListView(generic.ListView):
    model = Author
    template_name = "aggregation/author_list.html"
    # paginate_by = 10
    queryset = Author.objects.annotate(num=Count("book__id"))
    context_object_name = "authors_books"

    def get_queryset(self):
        return super().get_queryset().order_by('name')


class PublisherListView(generic.ListView):
    model = Publisher
    template_name = "aggregation/publisher_list.html"
    # paginate_by = 10
    queryset = Publisher.objects.annotate(num=Count("book__id"))
    context_object_name = "publishers_books"

    def get_queryset(self):
        return super().get_queryset().order_by('name')


class StoreListView(generic.ListView):
    model = Store
    template_name = "aggregation/store_list.html"
    # paginate_by = 10
    queryset = Store.objects.annotate(num=Count("books__id"))
    context_object_name = "stores_books"

    def get_queryset(self):
        return super().get_queryset().order_by('name')


# Detail Views
class CacheMixin(object):
    cache_timeout = 60

    def dispatch(self, *args, **kwargs):
        return cache_page(self.cache_timeout)(
            super(CacheMixin, self).dispatch)(*args, **kwargs)


class AuthorDetailView(CacheMixin, generic.DetailView):
    cache_timeout = 10
    model = Author
    template_name = "aggregation/author_detail.html"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(AuthorDetailView, self).get_context_data(**kwargs)
        book_author = Book.objects.filter(authors__id=self.object.id).annotate(num=Count("id"))
        context['author_books'] = book_author

        # Экономия одного запроса -- стоит ли len?
        context['written_total'] = len(book_author)
        # context['written_total'] = book_author.count()

        # Здесь prefetch_related("authors") экономии не дает, его можно убрать?
        context['author_avg_rating'] = round(Book.objects.prefetch_related("authors").filter(
                                authors=self.object.id).aggregate(a=Avg("rating"))["a"], 2)
        # context['author_avg_rating'] = round(Book.objects.filter(
        #     authors=self.object.id).aggregate(a=Avg("rating"))["a"], 2)
        return context


class PublisherDetailView(generic.DetailView):
    model = Publisher
    template_name = "aggregation/publisher_detail.html"

    def get_context_data(self, **kwargs):
        context = super(PublisherDetailView, self).get_context_data(**kwargs)
        context['published_total'] = Book.objects.filter(publisher=self.object.id).count()
        context['publisher_books'] = Book.objects.filter(publisher=self.object.id)
        context['publisher_avg_rating'] = round(Book.objects.filter(
                                publisher=self.object.id).aggregate(a=Avg("rating"))["a"], 2)
        return context


class BookDetailView(generic.DetailView):
    model = Book
    template_name = "aggregation/book_detail.html"

    def get_context_data(self, **kwargs):
        context = super(BookDetailView, self).get_context_data(**kwargs)
        context['available_stores'] = Store.objects.filter(books=self.object.id)
        context['books_authors'] = Author.objects.filter(book=self.object.id)
        return context


class StoreDetailView(generic.DetailView):
    model = Store
    template_name = "aggregation/store_detail.html"
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(StoreDetailView, self).get_context_data(**kwargs)
        context['store_books'] = Book.objects.filter(store=self.object.id)
        context['selling_total'] = Book.objects.filter(store=self.object.id).count()
        return context


def reminder_form(request):
    now = timezone.now()
    if request.method == "POST":
        form = ReminderForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            reminder_text = form.cleaned_data.get("reminder_text")
            date_time = form.cleaned_data.get("date_time")
            tasks.reminder_task.apply_async(kwargs={"email": email, "reminder_text": reminder_text},
                                            eta=date_time)
            return redirect(reverse("aggregation:index"))
    else:
        form = ReminderForm(initial={"email": "example@dj.com", "date_time": now, "reminder_text": "Reminder"})
    return render(request, "aggregation/reminder_form.html", {"form": form})


# HW-16 =====================================================
class BookCreateView(LoginRequiredMixin, CreateView):
    raise_exception = True
    template_name = "aggregation/book_create.html"
    now = datetime.now()
    model = Book
    fields = ['name', 'pages', 'price', 'rating', 'authors', 'publisher', 'pubdate']
    initial = {'name': "book name", 'pages': 123, 'price': 9.99, 'rating': 10, 'pubdate': now}
    success_url = reverse_lazy("aggregation:book-list")


class BookUpdateView(LoginRequiredMixin, UpdateView):
    raise_exception = True
    template_name = "aggregation/book_update.html"
    model = Book
    fields = ['name', 'pages', 'price', 'rating', 'authors', 'publisher', 'pubdate']
    success_url = reverse_lazy("aggregation:book-list")


class BookDeleteView(LoginRequiredMixin, DeleteView):
    raise_exception = True
    model = Book
    template_name = "aggregation/book_confirm_delete.html"
    success_url = reverse_lazy("aggregation:book-list")


class ContactFormView(FormView):
    template_name = 'aggregation/contact_form.html'
    initial = {'first_name': "User", "last_name": "Userenko", "email_address": "uu@example.com"}
    form_class = ContactForm
    success_url = reverse_lazy('aggregation:contact-form-thanks')

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


class ContactTemplateView(generic.TemplateView):
    template_name = 'aggregation/contact_form_thanks.html'

aggregation/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Aggregate Application</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'base_project_page' %}">Base PROJECT Page</a></li>
<hr>
          <li><a href="{% url 'aggregation:index' %}">Home Aggregate App Page</a></li>
<hr>
          <li><a href="{% url 'aggregation:author-list' %}">All Authors</a></li>
          <li><a href="{% url 'aggregation:publisher-list' %}">All Publishers</a></li>
          <li><a href="{% url 'aggregation:book-list' %}">All Books</a></li>
          <li><a href="{% url 'aggregation:store-list' %}">All Stores</a></li>
<hr>
          <li><a href="{% url 'aggregation:reminder-form' %}">Reminder</a></li>

<hr>
          <li><a href="{% url 'aggregation:book-create' %}">Create Book</a></li>
<hr>
          <li><a href="{% url 'aggregation:contact-form' %}">Contact Form</a></li>

        </ul>

     {% endblock %}

      </div>
      <div class="col-sm-10 ">

        {% block content %}
        {% endblock %}

{#        {% block pagination %}#}
{#    {% if is_paginated %}#}
{#        <div class="pagination">#}
{#            <span class="page-links">#}
{#                {% if page_obj.has_previous %}#}
{#                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>#}
{#                {% endif %}#}
{#                <span class="page-current">#}
{#                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.#}
{#                </span>#}
{#                {% if page_obj.has_next %}#}
{#                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>#}
{#                {% endif %}#}
{#            </span>#}
{#        </div>#}
{#    {% endif %}#}
{#  {% endblock %}#}

{#{% for book in page_obj %}#}
{#    {{ book.name|upper }}<br>#}
{#    ...#}
{#{% endfor %}#}
{% block pagination %}
{% if is_paginated %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo</a>
        {% endif %}
    </span>
</div>
{% endif %}
{% endblock %}

      </div>
    </div>
  </div>
</body>
</html>

aggregation/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Aggregate App Index Page</title>
</head>
<body>

{% extends "base_generic.html" %}

{% block content %}
  <h1>Aggregate App Home Page</h1>
  <p>Welcome to <em>Aggregate App</em>!</p>
  <h2>Dynamic content</h2>
  <p>There are the following record counts:</p>
  <ul>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Publishers:</strong> {{ num_publishers }}</li>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Stores:</strong> {{ num_stores }}</li>

  </ul>
    <p>You have visited this page for {{ num_visits }} times.</p>

{% endblock %}

</body>
</html>